kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceName }}-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "{{ cookiecutter.service_slug }}.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.serviceName }}-reader-role
  apiGroup: ""